// for appreducer
export const GENERATING_MNEMONIC = "GENERATING_MNEMONIC";
export const UPDATING_CONTRACT_BALANCE = "UPDATING_CONTRACT_BALANCE";
export const DISPLAYING_PSEUDO_CONTRACT_BALANCE =
  "DISPLAYING_PSEUDO_CONTRACT_BALANCE";
